### PR TITLE
Update

### PR DESCRIPTION
**Pull request by yuyuvn**

### CODE REVIEW

**Comment by blazeu** [comment]
`robot.hear` and `robot.respond` is not working on my side when using this.

Weird.

**Comment by yuyuvn** [comment]
did you use different account? hubot won't respond to itself

**Comment by blazeu** [comment]
Yes.

**Comment by yuyuvn** [comment]
then check your installed facebook-chat-api version, it can only work if version is 1.1.0 or newer

**Comment by blazeu** [comment]
It is.

Messages is received, only the listener is not called, i've tested the listener using shell adapter and it's working fine.

I know you added [this](https://github.com/blazeu/hubot-facebook/blob/c604108fa51e2f2a61a9d336f806975a899c0220/src/facebook.coffee#L180-L181), so i tested it with a group chat, but it's still not working.

Is it because of my node version? (i'm using v6)

**Comment by yuyuvn** [comment]
what is your installed hubot version?

**Comment by blazeu** [comment]
My hubot is 2.18.0, but the hubot from this package is 2.13.2.

I think the hubot from this package is what causes the trouble.
The adapter doesn't depend on hubot IIRC.

**Comment by yuyuvn** [comment]
I have created fix here: #2
hubot is needed to run test so I move it to devDependencies

**Comment by blazeu** [comment]
Also, what's [this](https://github.com/blazeu/hubot-facebook/blob/c604108fa51e2f2a61a9d336f806975a899c0220/src/facebook.coffee#L83-L121) for?

**Comment by yuyuvn** [comment]
I want to move message process to this method, don't know why it still inside listen callback

**Comment by blazeu** [comment]
Also, you could merge pull request (or push directly) on your own if you want.

**Pull request merged**
